// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
package main
 
import (
"fmt"
"net/http"
"io/ioutil"
"os"
)

func main() {
	req, err := http.NewRequest("GET", "https://api.github.com/orgs/clouddrove/repos?per_page=10&page=1", nil)
	if err != nil {
		// handle err
	}
	req.Header.Set("Authorization", "token 875bc57877f615dd985481c9ffe7f1148b7ee14e")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	defer resp.Body.Close()
	body, _ := ioutil.ReadAll(resp.Body)
 	for _, b := range body {
	}
	fmt.Println(string(resp.Body))
}