---
name: toc        
on:
  Schedule:
    - cron: '45 22 * * MON'

  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Toc:
    name: 'toc update'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'create readme'
        uses: 'clouddrove/github-actions@master'
        with:  
          actions_subcommand: 'toc'
          # actions_subcommand: readme
          modules: 'terraform-aws,terraform-azure,terraform-gcp,docker,ansible,tools'
          username: 'clouddrove.ci'
          email: 'clouddrove.ci@clouddrove.com'
          github_token: ${{ secrets.GITHUB }}
          
      - name: 'push readme'
        uses: 'clouddrove/github-actions@v9.0.2'
        continue-on-error: true
        with:
          actions_subcommand: 'push'
        env:
          github_token: ${{ secrets.GITHUB }}
...
